sudo: enabled
language: java
jdk:
  - openjdk8

services:
  - docker
  
branches:
  only:
    - develop-gcr

cache:
  directories:
  - '$HOME/.m2/repository'
env:

before_install:
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && chmod +x skaffold && sudo mv skaffold /usr/local/bin/
  #[Start Authorize]
  - cp $SERVICE_HOME/client_api_key.json $SERVICE_HOME/api_key.json
  - sed -i "s/PROJECT_ID/$PROJECT_ID/g" api_key.json
  - sed -i "s/PRIVATE_KEY_ID/$PRIVATE_KEY_ID/g" api_key.json
  - sed -i "s/PRIVATE_KEY/$PRIVATE_KEY/g" api_key.json
  - sed -i "s/CLIENT_EMAIL/$CLIENT_EMAIL/g" api_key.json
  - sed -i "s/CLIENT_ID/$CLIENT_ID/g" api_key.json
  - cd $SERVICE_HOME
  - cat api_key.json
  - export GOOGLE_APPLICATION_CREDENTIALS="$SERVICE_HOME/api_key.json"
  #[End Authorize]

after_install:
  #[Attempt Authorize]
  - gcloud auto activate-service-account --key-file ${GOOGLE_APPLICATION_CREDENTIALS}

script:
  - cd ${SERVICE_HOME}/config-server
  - skaffold run -p dev
  - cd ../users-detail-service
  - skaffold run -p dev
  - cd ../users-service
  - skaffold dev -p dev

after_script:
  - cd $SERVICE_HOME
  - rm api_key.json
 
