apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy:
    dateTime:
      format: "2020-05-13_13-13-32.999_MST"
      timezone: "Local"
  artifacts:
    - image: atropos0116/config-server
      docker:
        dockerfile: config-server/Dockerfile
    - image: atropos0116/users-service
      docker:
        dockerfile: users-service/Dockerfile	
    - image: atropos0116/users-detail-service
      docker:
        dockerfile: users-detail-service/Dockerfile
  local: {}

deploy:
  kubectl:
    manifests:
      - 'config-server/*-dev.yml'
      - 'users-service/*-dev.yml'
      - 'users-detail-service/*-dev.yml'
     
profiles:
- name: dev
  activation:
    - kubeContext: minikube
  deploy:
      kubectl:
        manifests:
          - 'config-server/*-dev.yml'
          - 'users-service/*-dev.yml'
          - 'users-detail-service/*-dev.yml'
- name: stg
  activation:
    - kubeContext: minikube
  deploy:
      kubectl:
        manifests:
          - 'config-server/*-stg.yml'
          - 'users-service/*-stg.yml'
          - 'users-detail-service/*-stg.yml'
      