apiVersion: skaffold/v1
kind: Config
build:
  googleCloudBuild:
    projectId: nifty-inn-274523
  tagPolicy:
    dateTime:
      format: "2020-05-13_13-13-32.999_MST"
      timezone: "Local"
  artifacts:
    - image: gcr.io/nifty-inn-274523/config-server
      docker:
        dockerfile: config-server/Dockerfile
    - image: gcr.io/nifty-inn-274523/users-service
      docker:
        dockerfile: users-service/Dockerfile	
    - image: gcr.io/nifty-inn-274523/users-detail-service
      docker:
        dockerfile: users-detail-service/Dockerfile

deploy:
  kubectl:
    manifests:
      - 'config-server/*-dev.yml'
      - 'users-service/*-dev.yml'
      - 'users-detail-service/*-dev.yml'
      
profiles:
- name: dev
  deploy:
      kubectl:
        manifests:
          - 'config-server/*-dev.yml'
          - 'users-service/*-dev.yml'
          - 'users-detail-service/*-dev.yml'
- name: stg
  deploy:
      kubectl:
        manifests:
          - 'config-server/*-stg.yml'
          - 'users-service/*-stg.yml'
          - 'users-detail-service/*-stg.yml'
      