apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
---
apiVersion: v1
kind: Service
metadata:
  name: users-postgres
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - port: 5432
  clusterIP: 10.101.56.2
  selector:
    app: postgres
---
kind: Service
apiVersion: v1
metadata:
  name: users-service
  namespace: dev
spec:
  selector:
    app: users-service
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30086
  type: NodePort

