apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: users-postgres-config
  namespace: dev
data:
  postgres_host: 10.113.10.100
  postgres_user: admin
  postgres_password: c1oudc0w
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: detail-postgres-config
  namespace: dev
data:
  postgres_host: 10.113.10.101
  postgres_user: admin
  postgres_password: c1oudc0w
