apiVersion: v1
kind: ConfigMap
metadata:
  name: users-postgres-config
  namespace: default
data:
  postgres_user: admin
  postgres_password: c1oudc0w
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: detail-postgres-config
  namespace: default
data:
  postgres_user: admin
  postgres_password: c1oudc0w
