kind: Service
apiVersion: v1
metadata:
  name: config-server
  namespace: stg
spec:
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30085
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: stg

spec:
  selector:
    matchLabels:
      app: config-server
  replicas: 1
  template:
    metadata:
      name: config-server
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: gcr.io/nifty-inn-274523/config-server:v1
        env:
          - name: GOOGLE_APPLICATION_CRENDENTIALS
            value: var/secrets/google/client_api_key.json
