apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: gcr.io/nifty-inn-274523/config-server
      kaniko:
        dockerfile: Dockerfile
        image: gcr.io/nifty-inn-274523/config-server
  googleCloudBuild:
    projectId: nifty-inn-274523
    dockerImage: gcr.io/cloud-builders/docker

deploy:
  kubectl:
    manifests:
      - 'config-server/*-dev.yml'
profiles:
- name: dev
  deploy:
      kubectl:
        manifests:
          - 'config-server/*-dev.yml'
- name: stg
  deploy:
      kubectl:
        manifests:
          - 'config-server/*-stg.yml'

