apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: detail-postgres-pv-claim
  namespace: stg
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
---
apiVersion: v1
kind: Service
metadata:
  name: detail-postgres
  namespace: stg
spec:
  type: ClusterIP
  ports:
    - port: 5432
  clusterIP: 10.113.10.101
  selector:
    app: detail-postgres
---
kind: Service
apiVersion: v1
metadata:
  name: users-detail-service
  namespace: stg
spec:
  selector:
    app: users-detail-service
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30087
  type: NodePort
