apiVersion: apps/v1
kind: Deployment
metadata:
  name: detail-postgres
  namespace: stg
spec:
  selector:
    matchLabels:
      app: detail-postgres
  template:
    metadata:
      labels:
        app: detail-postgres
    spec:
      volumes:
        - name: detail-postgres-storage
          persistentVolumeClaim:
            claimName: detail-postgres-pv-claim
      containers:
        - image: postgres
          name: postgres
          livenessProbe:
            exec:
              command:
                - psql
                - -w
                - -U
                - admin
                - -d
                - postgres
                - -c
                - 'SELECT 1'
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
                - psql
                - -w
                - -U
                - admin
                - -d
                - postgres
                - -c
                - 'SELECT 1'
            timeoutSeconds: 10
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: detail-postgres-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: detail-postgres-config
                  key: postgres_password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: detail-postgres
          volumeMounts:
            - name: detail-postgres-storage
              mountPath: /var/lib/postgresql/data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-detail-service
  namespace: stg

spec:
  selector:
    matchLabels:
      app: users-detail-service
  replicas: 1
  template:
    metadata:
      name: users-detail-service
      labels:
        app: users-detail-service
    spec:
      containers:
      - name: users-detail-service
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 10
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: detail-postgres-config
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: detail-postgres-config
                key: postgres_password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: detail-postgres-config
                key: postgres_host
        image: gcr.io/nifty-inn-274523/users-detail-service:v1
        ports:
          - containerPort: 8081
